version: '2'

services:
  app:
    tty: true
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 3008:3000

volumes:
  node_modules: